"""
stats_engine.py — Day 3 statistics + hypothesis engine
======================================================

Consumes the cleaned DataFrame + genotype groups from ingestion.py and turns them
into transparent, citation-backed hypothesis cards.

Agent-ready tools:
    compute_group_summary(df, biomarkers, scheme)      -> dict
    compute_subject_slopes(df, biomarker)              -> DataFrame
    compare_biomarker_trajectories(df, biomarker, scheme) -> dict
    analyze(df, biomarker, scheme)                     -> dict   (bundle)
    make_hypothesis_card(bundle)                       -> dict   (Hypothesis/Evidence/Caution/Citations)
    run_hypothesis(df, biomarker, scheme)              -> dict   (analyze + card)

Statistics are deliberately simple and interpretable for an MVP:
  * cross-sectional group comparison at BASELINE (avoids pseudo-replication),
  * per-subject OLS slopes then a between-group test for longitudinal change,
  * an age/sex-ADJUSTED effect via multiple regression at baseline.
The card auto-attaches the correct cautions (observational, synthetic-data,
small-n, rare-variant, per-subject-slope simplification) and REAL citations from a
curated set — nothing is generated by the LLM, so references can't be hallucinated.
"""

from __future__ import annotations

from typing import Dict, List, Union

import numpy as np
import pandas as pd
from scipy import stats

from ingestion import group_by_genotype, AMYLOID_POSITIVITY_CENTILOID


# --------------------------------------------------------------------------- #
# Metadata & curated citations (REAL references; attach by relevance)
# --------------------------------------------------------------------------- #
BIOMARKER_META = {
    "amyloid_centiloid":    {"higher_is_worse": True,  "unit": "CL",   "label": "amyloid burden"},
    "tau_suvr":             {"higher_is_worse": True,  "unit": "SUVR", "label": "tau burden"},
    "fdg_suvr":             {"higher_is_worse": False, "unit": "SUVR", "label": "FDG metabolism"},
    "hippocampal_volume":   {"higher_is_worse": False, "unit": "mm³",  "label": "hippocampal volume"},
    "entorhinal_thickness": {"higher_is_worse": False, "unit": "mm",   "label": "entorhinal thickness"},
    "mmse":                 {"higher_is_worse": False, "unit": "pts",  "label": "MMSE"},
    "cdrsb":                {"higher_is_worse": True,  "unit": "pts",  "label": "CDR-SB"},
}

CITATIONS = {
    "bateman2012": "Bateman RJ et al. Clinical and biomarker changes in dominantly inherited Alzheimer's disease. N Engl J Med. 2012;367(9):795-804.",
    "jack2010": "Jack CR Jr et al. Hypothetical model of dynamic biomarkers of the Alzheimer's pathological cascade. Lancet Neurol. 2010;9(1):119-128.",
    "jack2024": "Jack CR Jr et al. Revised criteria for diagnosis and staging of Alzheimer's disease (Alzheimer's Association Workgroup). Alzheimers Dement. 2024;20(8):5143-5169.",
    "corder1993": "Corder EH et al. Gene dose of apolipoprotein E type 4 allele and the risk of Alzheimer's disease in late onset families. Science. 1993;261(5123):921-923.",
    "jonsson2013": "Jonsson T et al. Variant of TREM2 associated with the risk of Alzheimer's disease. N Engl J Med. 2013;368(2):107-116.",
    "oasis3_2019": "LaMontagne PJ et al. OASIS-3: Longitudinal neuroimaging, clinical, and cognitive dataset for normal aging and Alzheimer disease. medRxiv 2019.12.13.19014902.",
}


# --------------------------------------------------------------------------- #
# Small OLS with confidence intervals (numpy + scipy; no statsmodels needed)
# --------------------------------------------------------------------------- #
def _ols(X: np.ndarray, y: np.ndarray, names: List[str]) -> dict:
    """Ordinary least squares with 95% CIs and two-sided p-values.

    X must already include an intercept column. Returns per-term estimates.
    """
    X = np.asarray(X, float)
    y = np.asarray(y, float)
    n, p = X.shape
    dof = n - p
    XtX_inv = np.linalg.pinv(X.T @ X)
    beta = XtX_inv @ X.T @ y
    resid = y - X @ beta
    sigma2 = (resid @ resid) / dof if dof > 0 else np.nan
    se = np.sqrt(np.diag(sigma2 * XtX_inv))
    tvals = beta / se
    pvals = 2 * stats.t.sf(np.abs(tvals), dof)
    tcrit = stats.t.ppf(0.975, dof)
    out = {}
    for i, name in enumerate(names):
        out[name] = {
            "coef": float(beta[i]),
            "se": float(se[i]),
            "t": float(tvals[i]),
            "p_value": float(pvals[i]),
            "ci95": [float(beta[i] - tcrit * se[i]), float(beta[i] + tcrit * se[i])],
        }
    out["_n"] = int(n)
    out["_dof"] = int(dof)
    return out


def _cohens_d(a: np.ndarray, b: np.ndarray) -> float:
    a, b = np.asarray(a, float), np.asarray(b, float)
    na, nb = len(a), len(b)
    if na < 2 or nb < 2:
        return float("nan")
    sp = np.sqrt(((na - 1) * a.var(ddof=1) + (nb - 1) * b.var(ddof=1)) / (na + nb - 2))
    return float((a.mean() - b.mean()) / sp) if sp > 0 else float("nan")


def _welch(a: np.ndarray, b: np.ndarray) -> dict:
    """Welch's t-test + mean difference with 95% CI."""
    a = np.asarray(a, float); a = a[~np.isnan(a)]
    b = np.asarray(b, float); b = b[~np.isnan(b)]
    if len(a) < 2 or len(b) < 2:
        return {"insufficient_n": True, "n_a": len(a), "n_b": len(b)}
    t, p = stats.ttest_ind(a, b, equal_var=False)
    diff = a.mean() - b.mean()
    se = np.sqrt(a.var(ddof=1) / len(a) + b.var(ddof=1) / len(b))
    dof = se**4 / ((a.var(ddof=1)/len(a))**2/(len(a)-1) + (b.var(ddof=1)/len(b))**2/(len(b)-1))
    tcrit = stats.t.ppf(0.975, dof)
    return {
        "mean_a": float(a.mean()), "mean_b": float(b.mean()),
        "n_a": int(len(a)), "n_b": int(len(b)),
        "mean_diff": float(diff), "diff_ci95": [float(diff - tcrit*se), float(diff + tcrit*se)],
        "t": float(t), "p_value": float(p), "cohens_d": _cohens_d(a, b),
    }


# --------------------------------------------------------------------------- #
# 1. compute_group_summary
# --------------------------------------------------------------------------- #
def compute_group_summary(df: pd.DataFrame, biomarkers: Union[List[str], None] = None,
                          scheme: str = "e4_dose", baseline_only: bool = True) -> dict:
    """Descriptive statistics (n, mean, median, sd) per genotype group.

    For amyloid_centiloid it also reports the % above the positivity threshold.
    Uses baseline visits by default to avoid counting repeat visits as independent.
    """
    biomarkers = biomarkers or list(BIOMARKER_META)
    data = df[df["visit_month"] == 0] if baseline_only else df
    groups = group_by_genotype(data, scheme)
    summary = {"scheme": scheme, "baseline_only": baseline_only, "groups": {}}
    for label, g in groups.items():
        entry = {"n_subjects": int(g["subject_id"].nunique()), "biomarkers": {}}
        for bm in biomarkers:
            if bm not in g:
                continue
            s = pd.to_numeric(g[bm], errors="coerce").dropna()
            if len(s) == 0:
                continue
            stat = {"n": int(len(s)), "mean": round(float(s.mean()), 3),
                    "median": round(float(s.median()), 3), "sd": round(float(s.std(ddof=1)), 3)}
            if bm == "amyloid_centiloid":
                stat["pct_amyloid_positive"] = round(float((s > AMYLOID_POSITIVITY_CENTILOID).mean()*100), 1)
            entry["biomarkers"][bm] = stat
        summary["groups"][label] = entry
    return summary


# --------------------------------------------------------------------------- #
# 2. compute_subject_slopes
# --------------------------------------------------------------------------- #
def compute_subject_slopes(df: pd.DataFrame, biomarker: str, min_visits: int = 2) -> pd.DataFrame:
    """Per-subject OLS slope of a biomarker over time (units per YEAR).

    Subjects with fewer than `min_visits` non-missing measurements are skipped.
    Returns columns: subject_id, apoe_e4_count, trem2_variant_status, slope,
    n_visits, span_years.
    """
    rows = []
    for sid, sub in df.groupby("subject_id"):
        s = sub.dropna(subset=[biomarker])
        if s["visit_month"].nunique() < min_visits:
            continue
        x = s["visit_month"].to_numpy(float) / 12.0
        y = pd.to_numeric(s[biomarker], errors="coerce").to_numpy(float)
        slope = float(np.polyfit(x, y, 1)[0])
        rows.append({
            "subject_id": sid,
            "apoe_e4_count": int(sub["apoe_e4_count"].iloc[0]),
            "trem2_variant_status": sub["trem2_variant_status"].iloc[0],
            "slope": slope, "n_visits": int(s["visit_month"].nunique()),
            "span_years": round(float(x.max() - x.min()), 2),
        })
    return pd.DataFrame(rows)


# --------------------------------------------------------------------------- #
# 3. cross-sectional + adjusted effect + trajectory comparison
# --------------------------------------------------------------------------- #
def _grouping_series(df: pd.DataFrame, scheme: str) -> pd.Series:
    if scheme == "e4_carrier":
        return (df["apoe_e4_count"] >= 1).map({True: "e4_carrier", False: "e4_noncarrier"})
    if scheme == "trem2":
        return df["trem2_variant_status"]
    return df["apoe_e4_count"].astype(str).radd("e4=")


def compare_cross_sectional(df: pd.DataFrame, biomarker: str, scheme: str = "e4_carrier") -> dict:
    """Baseline group comparison. For e4_carrier/trem2: Welch's test + Cohen's d.
    For e4_dose: linear trend (biomarker ~ e4 allele count)."""
    base = df[df["visit_month"] == 0]
    if scheme == "e4_dose":
        d = base.dropna(subset=[biomarker, "apoe_e4_count"])
        X = np.column_stack([np.ones(len(d)), d["apoe_e4_count"].to_numpy(float)])
        res = _ols(X, pd.to_numeric(d[biomarker]).to_numpy(float), ["intercept", "per_e4_allele"])
        return {"type": "linear_trend", "biomarker": biomarker,
                "per_e4_allele": res["per_e4_allele"], "n": res["_n"]}
    grp = _grouping_series(base, scheme)
    labels = [l for l in grp.dropna().unique()]
    carrier = base.loc[grp == labels[0], biomarker] if labels else pd.Series(dtype=float)
    # order carrier/first vs non
    a_label = "e4_carrier" if scheme == "e4_carrier" else "R47H_carrier"
    b_label = "e4_noncarrier" if scheme == "e4_carrier" else "noncarrier"
    a = pd.to_numeric(base.loc[grp == a_label, biomarker], errors="coerce")
    b = pd.to_numeric(base.loc[grp == b_label, biomarker], errors="coerce")
    return {"type": "group_contrast", "biomarker": biomarker,
            "group_a": a_label, "group_b": b_label, **_welch(a, b)}


def adjusted_effect(df: pd.DataFrame, biomarker: str, scheme: str = "e4_carrier") -> dict:
    """Age/sex-adjusted baseline effect via multiple regression.

    biomarker ~ genetic_term + age + sex(male=1). Reports the genetic coefficient,
    demonstrating the effect survives (or not) after controlling for age and sex.
    """
    base = df[df["visit_month"] == 0].copy()
    base["_male"] = (base["sex"].astype(str).str.upper() == "M").astype(float)
    if scheme == "trem2":
        base["_gene"] = (base["trem2_variant_status"] == "R47H_carrier").astype(float)
        gene_name = "trem2_R47H"
    elif scheme == "e4_carrier":
        base["_gene"] = (base["apoe_e4_count"] >= 1).astype(float)
        gene_name = "e4_carrier"
    else:
        base["_gene"] = base["apoe_e4_count"].astype(float)
        gene_name = "per_e4_allele"
    d = base.dropna(subset=[biomarker, "_gene", "age", "_male"])
    if len(d) < 10:
        return {"insufficient_n": True, "n": int(len(d))}
    X = np.column_stack([np.ones(len(d)), d["_gene"], d["age"], d["_male"]])
    y = pd.to_numeric(d[biomarker], errors="coerce").to_numpy(float)
    res = _ols(X, y, ["intercept", gene_name, "age", "sex_male"])
    return {"biomarker": biomarker, "gene_term": gene_name,
            "adjusted_effect": res[gene_name], "age": res["age"], "sex_male": res["sex_male"],
            "n": res["_n"]}


def compare_biomarker_trajectories(df: pd.DataFrame, biomarker: str,
                                   scheme: str = "e4_carrier") -> dict:
    """Compare per-subject longitudinal slopes between genotype groups."""
    slopes = compute_subject_slopes(df, biomarker)
    if scheme == "e4_dose":
        by = slopes.groupby("apoe_e4_count")["slope"].agg(["count", "mean", "std"]).round(3)
        d = slopes.dropna(subset=["slope"])
        X = np.column_stack([np.ones(len(d)), d["apoe_e4_count"].to_numpy(float)])
        res = _ols(X, d["slope"].to_numpy(float), ["intercept", "per_e4_allele"])
        return {"type": "slope_trend", "biomarker": biomarker,
                "group_slopes": by.reset_index().to_dict("records"),
                "per_e4_allele_slope": res["per_e4_allele"], "n_subjects": res["_n"]}
    if scheme == "e4_carrier":
        a = slopes.loc[slopes["apoe_e4_count"] >= 1, "slope"]
        b = slopes.loc[slopes["apoe_e4_count"] == 0, "slope"]
        a_label, b_label = "e4_carrier", "e4_noncarrier"
    else:
        a = slopes.loc[slopes["trem2_variant_status"] == "R47H_carrier", "slope"]
        b = slopes.loc[slopes["trem2_variant_status"] == "noncarrier", "slope"]
        a_label, b_label = "R47H_carrier", "noncarrier"
    return {"type": "slope_contrast", "biomarker": biomarker,
            "group_a": a_label, "group_b": b_label,
            "mean_slope_a": round(float(a.mean()), 3) if len(a) else None,
            "mean_slope_b": round(float(b.mean()), 3) if len(b) else None,
            **_welch(a, b)}


# --------------------------------------------------------------------------- #
# 4. analyze  (bundle) + make_hypothesis_card
# --------------------------------------------------------------------------- #
def analyze(df: pd.DataFrame, biomarker: str, scheme: str = "e4_carrier") -> dict:
    """Run cross-sectional, adjusted, and trajectory analyses for one biomarker."""
    return {
        "biomarker": biomarker, "scheme": scheme,
        "n_subjects": int(df["subject_id"].nunique()),
        "is_synthetic": bool(
            ("data_source" in df.columns and (df["data_source"] == "synthetic").any())
            or df["subject_id"].astype(str).str.startswith("SYN").all()),
        "cross_sectional": compare_cross_sectional(df, biomarker, scheme),
        "adjusted": adjusted_effect(df, biomarker, scheme),
        "trajectory": compare_biomarker_trajectories(df, biomarker, scheme),
    }


def _fmt_p(p):
    return "p<0.001" if p < 0.001 else f"p={p:.3f}"


def _cautions(bundle: dict, group_ns: List[int]) -> List[str]:
    c = ["Observational association, not causal evidence.",
         "Hypothesis-generating only; not for diagnosis or clinical prediction."]
    if bundle.get("is_synthetic"):
        c.insert(0, "Demonstrated on SYNTHETIC data — the effect direction is built "
                    "into the data generator by design and is not evidence about real biology.")
    if group_ns and min(group_ns) < 20:
        c.append(f"Small group size (min n={min(group_ns)} subjects); effect is exploratory "
                 "and confidence intervals are wide.")
    if bundle["scheme"] == "trem2":
        c.append("TREM2 R47H is rare, so this comparison is typically underpowered.")
    c.append("Longitudinal test uses per-subject OLS slopes; a linear mixed-effects model "
             "with unequal follow-up would be the confirmatory upgrade.")
    return c


def _pick_citations(bundle: dict) -> List[str]:
    ids = ["jack2024"]
    if bundle["scheme"] in ("e4_dose", "e4_carrier"):
        ids += ["corder1993", "jack2010", "bateman2012"]
    if bundle["scheme"] == "trem2":
        ids += ["jonsson2013"]
    if bundle["biomarker"] == "amyloid_centiloid":
        ids += ["oasis3_2019"]
    seen, out = set(), []
    for i in ids:
        if i not in seen:
            seen.add(i); out.append(CITATIONS[i])
    return out


def make_hypothesis_card(bundle: dict) -> dict:
    """Assemble a Hypothesis / Evidence / Caution / Citations card from an analyze() bundle."""
    bm = bundle["biomarker"]
    meta = BIOMARKER_META.get(bm, {"label": bm, "unit": "", "higher_is_worse": True})
    cs, adj, tr = bundle["cross_sectional"], bundle["adjusted"], bundle["trajectory"]
    evidence: List[str] = []
    group_ns: List[int] = []

    # cross-sectional evidence
    if cs.get("type") == "group_contrast" and not cs.get("insufficient_n"):
        group_ns += [cs["n_a"], cs["n_b"]]
        direction = "higher" if cs["mean_diff"] > 0 else "lower"
        evidence.append(
            f"At baseline, {cs['group_a']} had {direction} {meta['label']} than {cs['group_b']} "
            f"({cs['mean_a']:.2f} vs {cs['mean_b']:.2f} {meta['unit']}; "
            f"Δ={cs['mean_diff']:.2f}, 95% CI [{cs['diff_ci95'][0]:.2f}, {cs['diff_ci95'][1]:.2f}], "
            f"{_fmt_p(cs['p_value'])}, Cohen's d={cs['cohens_d']:.2f}).")
    elif cs.get("type") == "linear_trend":
        e = cs["per_e4_allele"]
        evidence.append(
            f"Baseline {meta['label']} changed by {e['coef']:.2f} {meta['unit']} per ε4 allele "
            f"(95% CI [{e['ci95'][0]:.2f}, {e['ci95'][1]:.2f}], {_fmt_p(e['p_value'])}).")

    # adjusted evidence
    if adj and not adj.get("insufficient_n"):
        ae = adj["adjusted_effect"]
        evidence.append(
            f"After adjusting for age and sex, the {adj['gene_term']} effect on {meta['label']} "
            f"was {ae['coef']:.2f} {meta['unit']} "
            f"(95% CI [{ae['ci95'][0]:.2f}, {ae['ci95'][1]:.2f}], {_fmt_p(ae['p_value'])}).")

    # trajectory evidence
    if tr.get("type") == "slope_contrast" and not tr.get("insufficient_n"):
        group_ns += [tr.get("n_a", 0), tr.get("n_b", 0)]
        evidence.append(
            f"Annual change ({meta['unit']}/yr) was {tr['mean_slope_a']} in {tr['group_a']} "
            f"vs {tr['mean_slope_b']} in {tr['group_b']} "
            f"(Δ={tr['mean_diff']:.3f}, 95% CI [{tr['diff_ci95'][0]:.3f}, {tr['diff_ci95'][1]:.3f}], "
            f"{_fmt_p(tr['p_value'])}, Cohen's d={tr['cohens_d']:.2f}).")
    elif tr.get("type") == "slope_trend":
        e = tr["per_e4_allele_slope"]
        evidence.append(
            f"Annual change in {meta['label']} shifted by {e['coef']:.3f} {meta['unit']}/yr per ε4 "
            f"allele (95% CI [{e['ci95'][0]:.3f}, {e['ci95'][1]:.3f}], {_fmt_p(e['p_value'])}).")

    gene_label = {"e4_dose": "APOE ε4 dose", "e4_carrier": "APOE ε4 carriers",
                  "trem2": "TREM2 R47H carriers"}[bundle["scheme"]]
    worse = "greater/worse" if meta["higher_is_worse"] else "lower/greater-decline in"
    hypothesis = (f"{gene_label} show {worse} {meta['label']} and/or faster longitudinal change "
                  f"than the comparison group.")

    return {
        "hypothesis": hypothesis,
        "evidence": evidence or ["Insufficient data to compute evidence for this comparison."],
        "caution": _cautions(bundle, group_ns),
        "citations": _pick_citations(bundle),
        "provenance": {"biomarker": bm, "scheme": bundle["scheme"],
                       "n_subjects": bundle["n_subjects"], "synthetic": bundle["is_synthetic"]},
    }


def run_hypothesis(df: pd.DataFrame, biomarker: str, scheme: str = "e4_carrier") -> dict:
    """One-call: run the analyses and return a formatted hypothesis card."""
    return make_hypothesis_card(analyze(df, biomarker, scheme))


def render_card_text(card: dict) -> str:
    """Human-readable rendering matching the Day 3 card format."""
    lines = ["Hypothesis:", "  " + card["hypothesis"], "", "Evidence:"]
    lines += [f"  - {e}" for e in card["evidence"]]
    lines += ["", "Caution:"] + [f"  - {c}" for c in card["caution"]]
    lines += ["", "References:"] + [f"  - {r}" for r in card["citations"]]
    return "\n".join(lines)


def rank_biomarkers(df: pd.DataFrame, scheme: str = "e4_carrier") -> dict:
    """Rank all analyzable biomarkers by the magnitude of their genotype effect.

    For carrier/TREM2 schemes the metric is |Cohen's d| of the baseline group contrast;
    for e4_dose it is the standardized per-allele slope (|beta| / baseline SD). Returns a
    list sorted by effect magnitude (largest first), with direction and p-value.
    """
    base = df[df["visit_month"] == 0]
    ranked = []
    for bm in BIOMARKER_META:
        if bm not in df.columns or pd.to_numeric(df[bm], errors="coerce").notna().sum() == 0:
            continue
        cs = compare_cross_sectional(df, bm, scheme)
        abs_effect = direction = p = None
        metric = None
        if cs.get("type") == "group_contrast" and not cs.get("insufficient_n"):
            d = cs.get("cohens_d")
            if d is not None and not np.isnan(d):
                abs_effect = abs(d)
                direction = "higher_in_carrier" if cs["mean_diff"] > 0 else "lower_in_carrier"
                p = cs["p_value"]; metric = "abs_cohens_d"
        elif cs.get("type") == "linear_trend":
            beta = cs["per_e4_allele"]["coef"]
            sd = pd.to_numeric(base[bm], errors="coerce").std(ddof=1)
            if sd and sd > 0:
                abs_effect = abs(beta / sd)
                direction = "increases_with_dose" if beta > 0 else "decreases_with_dose"
                p = cs["per_e4_allele"]["p_value"]; metric = "abs_std_beta_per_allele"
        if abs_effect is not None:
            ranked.append({"biomarker": bm, "label": BIOMARKER_META[bm]["label"],
                           "abs_effect": round(float(abs_effect), 3),
                           "direction": direction, "p_value": round(float(p), 4)})
    ranked.sort(key=lambda r: r["abs_effect"], reverse=True)
    for i, r in enumerate(ranked, 1):
        r["rank"] = i
    return {"scheme": scheme, "metric": ranked[0]["biomarker"] if ranked else None,
            "ranking": ranked}


if __name__ == "__main__":
    from ingestion import load_dataset, clean_biomarkers
    df, _ = clean_biomarkers(load_dataset("synthetic_adni_style.csv"))
    for bm, sch in [("amyloid_centiloid", "e4_dose"),
                    ("hippocampal_volume", "e4_carrier"),
                    ("mmse", "e4_carrier"),
                    ("hippocampal_volume", "trem2")]:
        print("=" * 78)
        print(f"[{sch}]  {bm}")
        print(render_card_text(run_hypothesis(df, bm, sch)))
